image: "ruby:2.6.3"

services:
  - postgres:11.4
  
variables:
  POSTGRES_DB: todo_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: root

stages:
  - build
  - test

before_script:
  - brew update -qq && brew install -y -qq pg libpq-dev nodejs
  - ruby -v
  - which ruby
  - gem install bundler --no-document
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

build:
  stage: build
  script:
    - echo "Building"

test:
  stage: test
  script:
    - echo "Testing"
    - bundle exec rake db:create db:schema:load RAILS_ENV=test
    - ruby -I test test/models/todo_item_test.rb
    - ruby -I test test/models/todo_list_test.rb
    - ruby -I test test/models/user_test.rb