image: "ruby:2.6"

stages:
  - build
  - test

before_script:
  - brew update -qq && brew install -y -qq pg libpq-dev nodejs
  - ruby -v
  - which ruby
  - gem install bundler --no-document
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

build:
  stage: build
  script:
    - echo "Building"

test:
  stage: test
  script:
    - echo "Testing"
    - ruby -I test test/models/todo_item_test.rb
    - ruby -I test test/models/todo_list_test.rb
    - ruby -I test test/models/user_test.rb