image: "ruby:2.6.3"

services:
  - postgres:11.4
  
variables:
  POSTGRES_DB: todo_test
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: root

stages:
  - test
  - deploy

before_script:
  - apt-get update -qq && apt-get install -y -qq postgresql postgresql-contrib libpq-dev cmake
  - ruby -v
  - which ruby
  - gem install bundler --no-document
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

#build:
#  stage: build
  #image: postgres
#  script:
#    - echo "Building"
#    - export PGPASSWORD=$POSTGRES_PASSWORD
#    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT 'OK' AS status;"


test:
  stage: test
  script:
    - echo "Testing"
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT 'OK' AS status;"
    - bundle exec rake db:create db:schema:load RAILS_ENV=test
    - bundle exec rspec
    
staging:
  type: deploy
  script:
  - gem install dpl
  - dpl --provider=heroku --app=rails-todo-staging --api-key=$HEROKU_STAGING_API_KEY
  - heroku run rake db:migrate --exit-code --app rails-todo-staging
  only:
  - master

production:
  type: deploy
  script:
  - gem install dpl
  - dpl --provider=heroku --app=rails-todo-production --api-key=$HEROKU_PRODUCTION_API_KEY
  - heroku run rake db:migrate --exit-code --app rails-todo-production
  only:
  - tags
